### ISSUE TITLE
Select2 not working when ng-show directive

### ISSUE THREAD

**Issue by iamvimuserbtw** [angular-ui/ui-select2#38] opened 2013-06-28 15:03 UTC
Hi,
I am having the same problem that issue #23 and followed your advice but even when the ng-show directive is on a parent element, it does not work for me : /

Do you have any idea why ?

**Comment by ProLoser** [comment] 2013-06-28 18:31
Duplicate of #23

**Closed as completed by ProLoser** 2013-06-28 18:31 UTC
