### ISSUE TITLE
$dirty is true when no changes were made and 'options' came via json array (or similar)

### ISSUE THREAD

**Issue by genuinefafa** [angular-ui/ui-select2#151] opened 2014-02-06 00:24 UTC
Following #6 that is closed and mostly https://github.com/angular-ui/angular-ui-OLDREPO/issues/268 (from the old repo). 

I'm using the latest _tagged_ version 0.0.5 and found that **$dirty** is always true when the form is loaded and the _options_ came via a json array. 

AFAIK It should be false if no changes were made.

Any clue on how to fix it? I made an example [plunkr](http://plnkr.co/edit/mcZnMQ).

**Comment by johnsouth** [comment] 2014-02-18 21:03
I just ran into the exact same issue myself. The solution I found required a slight tweak to the code. No PR because it's a quick hack with no testing and I suck at git. Sorry. :-/

So, find your existing $watch method and move the "elm.trigger('change');" line to within an "else" statement. If this breaks other stuff, feel free to tell me I'm horribly wrong, I only just figured this out a few minutes ago.

```
      // Watch the options dataset for changes
      if (watch) {
        scope.$watch(watch, function (newVal, oldVal, scope) {
          if (angular.equals(newVal, oldVal)) {
            return;
          }
          // Delayed so that the options have time to be rendered
          $timeout(function () {
            elm.select2('val', controller.$viewValue);

            if(newVal && !oldVal && controller.$setPristine) {
                controller.$setPristine(true);
            } else {
                // Refresh angular
                elm.trigger('change');
            }
          });
        });
      }
```

**Comment by micheee** [comment] 2014-05-06 12:58
:+1: to anyone could/knew how to fix this.

**Comment by vrodriguezTecsisa** [comment] 2014-05-07 10:51
+1

**Comment by HoffZ** [comment] 2014-05-07 12:04
+5000 (on the behalf of everyone using our app)

**Comment by HoffZ** [comment] 2014-05-08 07:38
Your hack is not working for me, @johnsouth. Could you apply your fix to the [Plunker](http://plnkr.co/edit/mcZnMQ) from @genuinefafa?

**Comment by ChristianGruen** [comment] 2014-05-10 14:12
Any chance to fix this soon?

**Comment by NMichas** [comment] 2014-05-13 06:23
Unfortunately, none of these solutions seem to work - including #173 and #208 .

**Comment by MilosMosovsky** [comment] 2014-05-14 18:06
@ChristianGruen @NMichas 
All of my problems was causing that i was initializing select2 on input type="text" try to change your code to input type="hidden" as it is triggering different events.

Tell me if it helps :)

**Comment by ChristianGruen** [comment] 2014-05-14 20:25
Thanks @Mavericker. Unfortunately, it doesn’t seem to help. In fact, `<input type="text"/>` doesn’t work at all; we need to use either `<div/>` or `<input type="hidden"/>`:

``` xml
<input type="hidden" ui-select2="settings.select2Options" ng-model="..."/>
```

``` javascript
$settings.select2Options = {
  multiple: true,
  ajax: { ... }
};
```

**Comment by MilosMosovsky** [comment] 2014-05-14 20:35
Are you able to post code where you have problems? I have already solved all problems inside my project. So maybe i will help you.

**Comment by ChristianGruen** [comment] 2014-05-14 20:38
Unfortunately not, but we’ll try to create a reproducible example. Thanks in advance!

**Comment by MilosMosovsky** [comment] 2014-05-14 20:55
Are you able to change 

https://github.com/angular-ui/ui-select2/blob/master/src/select2.js#L127

from 

``` javascript
  elm.trigger('change');
```

to

``` javascript
   controller.$render();
```

and

https://github.com/angular-ui/ui-select2/blob/master/src/select2.js#L209

from

``` javascript
   var isPristine = controller.$pristine;
            controller.$setViewValue(
              convertToAngularModel(elm.select2('data'))
            );
            if (isPristine) {
              controller.$setPristine();
            }
```

to

``` javascript

 var isPristine = controller.$pristine;
 controller.$pristine = false;
            controller.$setViewValue(
              convertToAngularModel(elm.select2('data'))
            );
            if (isPristine) {
              controller.$setPristine();
            }

```

**Comment by ChristianGruen** [comment] 2014-05-14 21:09
This could be the solution! I’ll do some more testing tomorrow and will let you know if everything works as expected…

**Comment by MilosMosovsky** [comment] 2014-05-14 21:12
I have it integrated inside approx 700-1000 select boxes and everything seems to be fine. When you will test it inside your app i will post new PR . Thanks for reply

**Comment by HoffZ** [comment] 2014-05-15 07:20
You're solution works for me, @Mavericker :thumbsup:

**Comment by MilosMosovsky** [comment] 2014-05-15 07:32
Thank you very much for response i will post PR today :)

**Comment by ChristianGruen** [comment] 2014-05-15 10:14
Confirmed; works fine ;)

**Comment by ChristianGruen** [comment] 2014-05-19 18:11
Sorry for pushing this… Did sth. go wrong in the pull request?

**Comment by MilosMosovsky** [comment] 2014-05-19 18:12
Nope i just forget :) Will make it tonight.

2014-05-19 20:11 GMT+02:00 Christian Gruen notifications@github.com:

**Comment by MilosMosovsky** [comment] 2014-05-21 17:52
Finally found time , here you are 
@ChristianGruen 
@HoffZ

**Comment by genuinefafa** [comment] 2014-05-21 20:58
I'm not sure if I shall test it again, or if you are going to release a new version now that this issue was solved. 

ps: I was silent, but not deft ;)

**Comment by MilosMosovsky** [comment] 2014-05-21 21:00
That fix is working , but somehow travis is failing with some bower error. I am not able to automatic merge it to master ....

**Comment by MilosMosovsky** [comment] 2014-05-21 21:15
@genuinefafa  Take PR #215 it is tested by Christian and HoffZ and also by me.

**Comment by arolle** [comment] 2014-05-23 14:26
Any news? Has this already been merged?

**Comment by MilosMosovsky** [comment] 2014-05-23 19:59
I cant merge it , but not because error but travis build is erroring due bower install. I am not able to merge it , even if all tests passed

https://travis-ci.org/angular-ui/ui-select2/builds/25719951

**Comment by ChristianGruen** [comment] 2014-05-24 10:14
Thanks for the feedback. Any chance to help you?

**Comment by MilosMosovsky** [comment] 2014-05-24 10:28
I cant find any contact to project maintaner to contact him about issues with build, if you can help me with that i would be happy :dancers:

**Comment by ChristianGruen** [comment] 2014-05-27 10:27
@Mavericker: I wrote to their mailing list. What do you think about the warning?.. https://groups.google.com/forum/#!topic/travis-ci/zGqeu3Uso9E

**Comment by MilosMosovsky** [comment] 2014-05-27 10:32
Hello i dont think it is commit related, because when you make clean FORK of latest ui-select2 master, and edit for example 1 line inside README.md. you will gete this error. So i think its related to ui-select2 build config..... or maybe travis is bugged.

Error is :
fstream_stack Object.oncomplete (fs.js:297:15)

npm ERR! Error: No compatible version found: minimatch@'^0.3.0'

npm ERR! Valid install targets:

npm ERR! ["0.0.1","0.0.2","0.0.4","0.0.5","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.2.0","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","0.2.12","0.2.13","0.2.14","0.3.0"]

But dependency is not required by my code, but from select2 itself. If you understand what i mean ....

**Comment by ChristianGruen** [comment] 2014-05-27 10:48
I think I understand. Do you know who’s responsible for the ui-select2 master and the build configuration?

**Comment by MilosMosovsky** [comment] 2014-05-27 10:53
I think https://github.com/ProLoser this guy , maybe contact him trough
contact form on his website??

2014-05-27 10:49 GMT+00:00 Christian Gruen notifications@github.com:

**Comment by ChristianGruen** [comment] 2014-05-29 11:26
...waiting for some feedback.

**Comment by shanesmith** [comment] 2014-07-18 05:42
I've confirmed that PR #215 fixes the issue for me. Any word from the maintainers?

**Comment by MilosMosovsky** [comment] 2014-07-18 06:01
i think they left this repo and started maintaining new version of select2 https://github.com/angular-ui/ui-select its native version without jquery and original select2, i can confirm that it works very well .... try to replace your select2 with the new one.

**Comment by genuinefafa** [comment] 2014-07-18 21:02
@MilosMosovsky do you think is the select2 native version is as stable as this one? I did a dry-run to a simple project and found it pretty slim. :(

**Comment by gpeshans** [comment] 2014-07-30 13:09
I made a new release that includes the fix proposed [here](https://github.com/angular-ui/ui-select2/issues/151#issuecomment-43136387) and it is available on bower by ['angular-nca-select2'](http://bower.io/search/?q=angular-nca-select2). There is also a minified version in the release. We use this as a temporary solution in our project and it will be deleted when a new version of angular-ui-select2 is published. Thanks @MilosMosovsky :)

**Closed as completed** 2014-08-01 21:59 UTC

**Comment by genuinefafa** [comment] 2014-08-01 22:52
@PesanskiGoran does your version differs from the uploaded here, how? I mean, the PR was accepted and is now _working_, is it not?

My project has some workaround for this issue. I need to do major changes now to test this. I would prefer having all the required information first :bowtie:

**Comment by philippd** [comment] 2014-08-04 18:15
@genuinefafa The pull request is now in the master, but there is no release available yet. The version from @PesanskiGoran is based on the latest master (including the fix described above) and contains also a minified version of angular-ui-select2. The repo is only a temporary workaround for us until the fix is available in a version via bower.
